In [73]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv('bodyfat.csv')
df

Density  BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  \
0     1.0708     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   
1     1.0853      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   
2     1.0414     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   
3     1.0751     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   
4     1.0340     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   
..       ...      ...  ...     ...     ...   ...    ...      ...    ...   
247   1.0736     11.0   70  134.25   67.00  34.9   89.2     83.6   88.8   
248   1.0236     33.6   72  201.00   69.75  40.9  108.5    105.0  104.5   
249   1.0328     29.3   72  186.75   66.00  38.9  111.1    111.5  101.7   
250   1.0399     26.0   72  190.75   70.50  38.9  108.3    101.3   97.8   
251   1.0271     31.9   74  207.50   70.00  40.8  112.4    108.5  107.1   

     Thigh  Knee  Ankle  Biceps  Forearm  Wrist  
0     59.0  37.3   21.9    32.0     27.4   17.1  
1     58.7  37.3   23.4    30.5     28.9   18.2  
2     59.6  38.9   24.0    28.8     25.2   16.6  
3     60.1  37.3   22.8    32.4     29.4   18.2  
4     63.2  42.2   24.0    32.2     27.7   17.7  
..     ...   ...    ...     ...      ...    ...  
247   49.6  34.8   21.5    25.6     25.7   18.5  
248   59.6  40.8   23.2    35.2     28.6   20.1  
249   60.3  37.3   21.5    31.3     27.2   18.0  
250   56.0  41.6   22.7    30.5     29.4   19.8  
251   59.3  42.2   24.6    33.7     30.0   20.9  

[252 rows x 15 columns]

In [75]:
df = df/df.max()
df

Density   BodyFat       Age    Weight    Height      Neck     Chest  \
0    0.965642  0.258947  0.283951  0.424756  0.871383  0.707031  0.683554   
1    0.978718  0.128421  0.271605  0.477076  0.929260  0.751953  0.687225   
2    0.939129  0.532632  0.271605  0.424067  0.852090  0.664062  0.703377   
3    0.969519  0.218947  0.320988  0.508743  0.929260  0.730469  0.747430   
4    0.932456  0.604211  0.296296  0.507366  0.916399  0.671875  0.714391   
..        ...       ...       ...       ...       ...       ...       ...   
247  0.968167  0.231579  0.864198  0.369682  0.861736  0.681641  0.654919   
248  0.923077  0.707368  0.888889  0.553490  0.897106  0.798828  0.796623   
249  0.931373  0.616842  0.888889  0.514250  0.848875  0.759766  0.815712   
250  0.937776  0.547368  0.888889  0.525265  0.906752  0.759766  0.795154   
251  0.926233  0.671579  0.913580  0.571389  0.900322  0.796875  0.825257   

      Abdomen       Hip     Thigh      Knee     Ankle    Biceps   Forearm  \
0    0.575287  0.639810  0.675830  0.759674  0.646018  0.711111  0.785100   
1    0.560432  0.668246  0.672394  0.759674  0.690265  0.677778  0.828080   
2    0.593518  0.671632  0.682703  0.792261  0.707965  0.640000  0.722063   
3    0.583390  0.685173  0.688431  0.759674  0.672566  0.720000  0.842407   
4    0.675219  0.689912  0.723940  0.859470  0.707965  0.715556  0.793696   
..        ...       ...       ...       ...       ...       ...       ...   
247  0.564483  0.601219  0.568156  0.708758  0.634218  0.568889  0.736390   
248  0.708980  0.707515  0.682703  0.830957  0.684366  0.782222  0.819484   
249  0.752870  0.688558  0.690722  0.759674  0.634218  0.695556  0.779370   
250  0.683997  0.662153  0.641466  0.847251  0.669617  0.677778  0.842407   
251  0.732613  0.725118  0.679267  0.859470  0.725664  0.748889  0.859599   

        Wrist  
0    0.799065  
1    0.850467  
2    0.775701  
3    0.850467  
4    0.827103  
..        ...  
247  0.864486  
248  0.939252  
249  0.841121  
250  0.925234  
251  0.976636  

[252 rows x 15 columns]

In [76]:
target = df.pop('BodyFat')
target

0      0.258947
1      0.128421
2      0.532632
3      0.218947
4      0.604211
         ...   
247    0.231579
248    0.707368
249    0.616842
250    0.547368
251    0.671579
Name: BodyFat, Length: 252, dtype: float64

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.2, random_state=42)

In [78]:
input_train = tf.convert_to_tensor(X_train)
input_test = tf.convert_to_tensor(X_test)
output_train = tf.convert_to_tensor(y_train)
output_test = tf.convert_to_tensor(y_test)

In [79]:
input_train

<tf.Tensor: shape=(201, 14), dtype=float64, numpy=
array([[0.94607268, 0.48148148, 0.45917665, ..., 0.72666667, 0.81088825,
        0.79906542],
       [0.94444945, 0.66666667, 0.54522924, ..., 0.79777778, 0.86532951,
        0.88317757],
       [0.92064208, 0.54320988, 0.61407132, ..., 0.77333333, 0.87965616,
        0.81308411],
       ...,
       [0.97348724, 0.58024691, 0.45504612, ..., 0.66888889, 0.80802292,
        0.85981308],
       [0.95617278, 0.48148148, 0.6464271 , ..., 0.86888889, 0.93123209,
        0.92990654],
       [0.94958968, 0.50617284, 0.47569875, ..., 0.68888889, 0.83667622,
        0.85981308]])>

In [80]:
num_features = len(input_train[0])
num_features

14

In [81]:
from keras.layers import ReLU
def create_model():
    return tf.keras.Sequential([
                Input(shape=(num_features,)),
                tf.keras.layers.Dense(128, activation='relu'),
                tf.keras.layers.Dense(64, activation='relu'),
                tf.keras.layers.Dense(32,activation='relu'),
                tf.keras.layers.Dense(1)
              ])


In [82]:
model = create_model()
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 128)               1920      
                                                                 
 dense_13 (Dense)            (None, 64)                8256      
                                                                 
 dense_14 (Dense)            (None, 32)                2080      
                                                                 
 dense_15 (Dense)            (None, 1)                 33        
                                                                 
Total params: 12289 (48.00 KB)
Trainable params: 12289 (48.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [93]:
def RMSE(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean((y_true - y_pred)**2))

adam = tf.keras.optimizers.Adam(learning_rate=0.1)

model.compile(optimizer=adam,loss=RMSE, metrics=RMSE)

In [94]:
epochs = 100
batch_size = 32
model.fit(input_train, output_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/100
6/6 [==============================] - 1s 15ms/step - loss: 0.1949 - RMSE: 0.1953 - val_loss: 0.1431 - val_RMSE: 0.1431
Epoch 2/100
6/6 [==============================] - 0s 6ms/step - loss: 0.1965 - RMSE: 0.1954 - val_loss: 0.1399 - val_RMSE: 0.1399
Epoch 3/100
6/6 [==============================] - 0s 9ms/step - loss: 0.1901 - RMSE: 0.1921 - val_loss: 0.1346 - val_RMSE: 0.1346
Epoch 4/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1898 - RMSE: 0.1916 - val_loss: 0.1305 - val_RMSE: 0.1305
Epoch 5/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1876 - RMSE: 0.1866 - val_loss: 0.1299 - val_RMSE: 0.1299
Epoch 6/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1877 - RMSE: 0.1874 - val_loss: 0.1316 - val_RMSE: 0.1316
Epoch 7/100
6/6 [==============================] - 0s 5ms/step - loss: 0.1872 - RMSE: 0.1872 - val_loss: 0.1301 - val_RMSE: 0.1301
Epoch 8/100
6/6 [==============================] - 0s 4ms/step - loss: 0.1921 - RM

In [95]:
loss, accuracy = model.evaluate(input_test, output_test,batch_size=batch_size)

2/2 [==============================] - 0s 2ms/step - loss: 0.1460 - RMSE: 0.1491


In [96]:
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Test Loss: 0.14598232507705688
Test Accuracy: 0.14912056922912598


In [100]:
!pip3 install pydot
tf.keras.utils.plot_model(model)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [102]:
model(input_train)

<tf.Tensor: shape=(201, 1), dtype=float32, numpy=
array([[0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
       [0.40842405],
     